spring.application.name=Doctors_service

spring.config.import=optional:file:./.env[.properties],optional:file:./services/Doctors_service/.env[.properties]

spring.profiles.active=dev

server.port=8083
