spring:
  application:
    name: API_Gateway

  codec:
    max-in-memory-size: 32MB

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      routes:

        - id: auth-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**

        - id: user-internal
          uri: http://user-service:8081
          predicates:
            - Path=/api/internal/**

        - id: uploads
          uri: http://user-service:8081
          predicates:
            - Path=/uploads/**

        - id: doctor-service
          uri: http://doctor-service:8083
          predicates:
            - Path=/api/doctors/**

        - id: doctor-verification
          uri: http://doctor-service:8083
          predicates:
            - Path=/api/doctor-verifications/**

        - id: doctor-conversation
          uri: http://doctor-service:8083
          predicates:
            - Path=/api/conversations/**

        - id: doctor-messages
          uri: http://doctor-service:8083
          predicates:
            - Path=/api/messages/**

        - id: derbel-service
          uri: http://derbel-service:8099
          predicates:
            - Path=/patients/**
            - Path=/records/**
            - Path=/prescriptions/**
            - Path=/medicines/**
            - Path=/dashboard/**

        - id: appointment-service
          uri: http://appointment-service:8091
          predicates:
            - Path=/api/appointments/**

        - id: whisper-service
          uri: http://whisper-service:5002
          predicates:
            - Path=/api/whisper/**

        - id: pharmacy-service
          uri: http://pharmacy-service:8093
          predicates:
            - Path=/api/pharmacy/**

        - id: insurance-service
          uri: http://insurance-service:8090
          predicates:
            - Path=/api/insurance/**

        - id: insurance-files
          uri: http://insurance-service:8090
          predicates:
            - Path=/api/files/**

        - id: websocket-user
          uri: ws://user-service:8081
          predicates:
            - Path=/ws/**

        - id: websocket-doctor-verification
          uri: ws://doctor-service:8083
          predicates:
            - Path=/ws-doctor-verification/**

        - id: websocket-contract
          uri: ws://doctor-service:8083
          predicates:
            - Path=/ws-approve-contract/**

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200"
              - "http://localhost:3000"
              - "http://192.168.1.247:32500"
              - "http://192.168.1.247:30080"
              - "http://192.168.1.236:30080"
              - "http://51.120.25.196:30080"
              - "http://serenity-frontend.norwayeast.cloudapp.azure.com"
              - "http://api.serenity.com"

            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS

            allowed-headers:
              - Authorization
              - Content-Type
              - Accept
              - Origin
              - X-Requested-With
              - Access-Control-Request-Method
              - Access-Control-Request-Headers

            allow-credentials: true

server:
  port: ${SERVER_PORT:8082}

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A47}
    expiration-ms: ${JWT_EXPIRATION:86400000}

debug: false
